version: '3'

services:
  db:
    image: 8769343ac885ab5fe04ba515dc06f92e6959e75357b328303f15849acf9ccd0d
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
      # - db_net
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # search:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
  #   environment:
  #     cluster.name: fusionauth
  #     bootstrap.memory_lock: "true"
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: ${FUSIONAUTH_ES_JAVA_OPTS}
  #   healthcheck:
  #     test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - search_net
  #   restart: unless-stopped
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - search_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      # search:
      #   condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/fusionauth
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DATABASE_ROOT_USERNAME: ${DB_POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      # SEARCH_SERVERS: http://search:9200
      # SEARCH_TYPE: elasticsearch

    networks:
      - db_net
      # - search_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  db_net:
    driver: bridge
  # search_net:
  #   driver: bridge

volumes:
  db_data:
  fusionauth_config:
  # search_data:
